
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REQUIREMENTS_END = 6;
  public static final int EXPERIMENT_BEGIN = 2;
  public static final int EXECUTION_END = 9;
  public static final int STRCONST = 36;
  public static final int DCONST = 35;
  public static final int DOUBLE = 14;
  public static final int CLOSE_SQUARE_BRACKETS = 31;
  public static final int INT = 13;
  public static final int CLOSE_ANGLE_BRACKETS = 33;
  public static final int SEMICOLON = 16;
  public static final int EXECUTION_BEGIN = 8;
  public static final int LT = 19;
  public static final int NODE_END = 11;
  public static final int INTCONST = 34;
  public static final int COMMA = 18;
  public static final int REQUIREMENTS_BEGIN = 5;
  public static final int PLUS = 22;
  public static final int MULTIPLY = 23;
  public static final int ASSIGN = 24;
  public static final int IF = 4;
  public static final int ID = 37;
  public static final int EOF = 0;
  public static final int OPEN_SQUARE_BRACKETS = 30;
  public static final int OPEN_ANGLE_BRACKETS = 32;
  public static final int error = 1;
  public static final int CLOSE_ROUND_BRACKETS = 27;
  public static final int EQ = 20;
  public static final int NAME = 25;
  public static final int EXPERIMENT_END = 3;
  public static final int COLON = 17;
  public static final int CLOSE_CURLY_BRACKETS = 29;
  public static final int WP = 12;
  public static final int NODE_BEGIN = 10;
  public static final int OPEN_ROUND_BRACKETS = 26;
  public static final int NODES = 7;
  public static final int STRING = 15;
  public static final int OPEN_CURLY_BRACKETS = 28;
  public static final int GT = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EXPERIMENT_BEGIN",
  "EXPERIMENT_END",
  "IF",
  "REQUIREMENTS_BEGIN",
  "REQUIREMENTS_END",
  "NODES",
  "EXECUTION_BEGIN",
  "EXECUTION_END",
  "NODE_BEGIN",
  "NODE_END",
  "WP",
  "INT",
  "DOUBLE",
  "STRING",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "LT",
  "EQ",
  "GT",
  "PLUS",
  "MULTIPLY",
  "ASSIGN",
  "NAME",
  "OPEN_ROUND_BRACKETS",
  "CLOSE_ROUND_BRACKETS",
  "OPEN_CURLY_BRACKETS",
  "CLOSE_CURLY_BRACKETS",
  "OPEN_SQUARE_BRACKETS",
  "CLOSE_SQUARE_BRACKETS",
  "OPEN_ANGLE_BRACKETS",
  "CLOSE_ANGLE_BRACKETS",
  "INTCONST",
  "DCONST",
  "STRCONST",
  "ID"
  };
}

